# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32fb5749f05f03e3fed1548d8c242b80a1c1381f88d88625d4ab6be14200388179eef30b096fc1b9d4515981dc1d9697c10328aa3427d36f74bbce74429947ad

test:
  secret_key_base: 6ab3ff43beafb9772e1f3f25873dc426d3f2ee5ca0a5c16fd6dd42033b2853878d75d566cb6b9d09ff5877140fc1f89ff253a7b684ddccbde1b989a3ba7614da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
